# Generated by Django 4.2.5 on 2023-09-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='название')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='аватар')),
                ('discription', models.TextField(blank=True, max_length=150, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='название')),
                ('discription', models.TextField(blank=True, max_length=150, null=True, verbose_name='описание')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='аватар')),
                ('url', models.URLField(blank=True, max_length=30, null=True, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
