# Generated by Django 4.2.5 on 2023-09-29 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='урок'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pay', models.DateField(auto_now_add=True, verbose_name='дата оплаты')),
                ('summa', models.PositiveIntegerField(default=0, verbose_name='сумма оплаты')),
                ('payment_method', models.CharField(choices=[('наличные', 'наличные'), ('перевод на счет', 'перевод на счет')], max_length=15, verbose_name='способ оплаты: наличные или перевод на счет')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'платёж',
                'verbose_name_plural': 'платежи',
            },
        ),
    ]
